/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ProductPrice, BaleOption } from "./types";

// Exchange rates relative to TZS (Tanzanian Shilling)
export const EXCHANGE_RATES = {
  TZS: 1.0,
  KES: 0.05, // 1 KES = 20 TZS
  USD: 0.00037, // 1 USD = 2,700 TZS
};

export function formatPrice(tzsAmount: number, currency: "TZS" | "KES" | "USD"): string {
  if (currency === "TZS") {
    return `${tzsAmount.toLocaleString()} TZS`;
  } else if (currency === "KES") {
    const kes = Math.round(tzsAmount * EXCHANGE_RATES.KES);
    return `${kes.toLocaleString()} KES`;
  } else {
    const usd = tzsAmount * EXCHANGE_RATES.USD;
    return `${usd.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 })} USD`;
  }
}

// Portmetals Africa Reviewed General Supplies Catalog
export const INITIAL_PRODUCTS: ProductPrice[] = [
  {
    id: 1,
    name: "Men Cotton Shirt",
    priceTZS: 27000,
    category: "Men's Fashion",
    baleSize: "45kg / 55kg",
    description: "Professionally sorted, light-pressed premium cotton shirts.",
    expectedProfitMargin: 0.65,
    resalePotential: "Sell individually at 45,000 TZS - 50,000 TZS",
    targetCustomer: "Office workers, formal wear boutiques",
  },
  {
    id: 2,
    name: "Men Mixed Pants",
    priceTZS: 18000,
    category: "Men's Fashion",
    baleSize: "45kg / 55kg",
    description: "Chinos, slacks, and casual trousers in outstanding condition.",
    expectedProfitMargin: 0.55,
    resalePotential: "Sell individually at 30,000 TZS - 35,000 TZS",
    targetCustomer: "Retail shops, students",
  },
  {
    id: 3,
    name: "Ladies Jeans",
    priceTZS: 15000,
    category: "Women's Fashion",
    baleSize: "45kg / 55kg",
    description: "Premium denim trousers including skinny, wide-leg, and boyfriend fits.",
    expectedProfitMargin: 0.70,
    resalePotential: "Sell individually at 25,000 TZS - 30,000 TZS",
    targetCustomer: "Instagram boutiques, open markets",
  },
  {
    id: 4,
    name: "Flanel Shirt",
    priceTZS: 15000,
    category: "Men's Fashion",
    baleSize: "45kg",
    description: "Classic plaid and checkered heavy flannel shirts.",
    expectedProfitMargin: 0.60,
    resalePotential: "Sell individually at 25,000 TZS - 28,000 TZS",
    targetCustomer: "Streetwear sellers, youth boutiques",
  },
  {
    id: 5,
    name: "Cotton Blouse (Brouse)",
    priceTZS: 10000,
    category: "Women's Fashion",
    baleSize: "45kg",
    description: "Airy, clean, and modern summer shirts and cotton blouses.",
    expectedProfitMargin: 0.80,
    resalePotential: "Sell individually at 18,000 TZS - 22,000 TZS",
    targetCustomer: "Office ladies, local traders",
  },
  {
    id: 6,
    name: "Shorts",
    priceTZS: 14000,
    category: "Men's Fashion",
    baleSize: "45kg",
    description: "Premium casual denim, khaki, and sports shorts.",
    expectedProfitMargin: 0.65,
    resalePotential: "Sell individually at 22,000 TZS - 25,000 TZS",
    targetCustomer: "Beach wear sellers, gym goers",
  },
  {
    id: 7,
    name: "Cotton Dress",
    priceTZS: 13000,
    category: "Women's Fashion",
    baleSize: "45kg / 55kg",
    description: "Sorted premium dresses, sun dresses, and midi casual dress options.",
    expectedProfitMargin: 0.75,
    resalePotential: "Sell individually at 22,000 TZS - 26,000 TZS",
    targetCustomer: "Boutique owners, retail markets",
  },
  {
    id: 8,
    name: "Hawaii [Palazo]",
    priceTZS: 12000,
    category: "Women's Fashion",
    baleSize: "45kg",
    description: "Flowy, high-waist palazzo trousers with tropical prints.",
    expectedProfitMargin: 0.70,
    resalePotential: "Sell individually at 20,000 TZS - 22,000 TZS",
    targetCustomer: "TikTok fashion stores, weekend markets",
  },
  {
    id: 9,
    name: "Anoraks / Zippers",
    priceTZS: 18000,
    category: "Jackets",
    baleSize: "45kg",
    description: "Light weather windbreakers and athletic zippers.",
    expectedProfitMargin: 0.50,
    resalePotential: "Sell individually at 28,000 TZS - 30,000 TZS",
    targetCustomer: "Boda-boda riders, outdoors active wear",
  },
  {
    id: 10,
    name: "Sweatshirts with Capchion",
    priceTZS: 15000,
    category: "Jackets",
    baleSize: "45kg",
    description: "Heavy hooded sweatshirts and winter pullovers.",
    expectedProfitMargin: 0.60,
    resalePotential: "Sell individually at 25,000 TZS - 30,000 TZS",
    targetCustomer: "Cool weather zones, university students",
  },
  {
    id: 11,
    name: "Baby Medium Rummage 25KG",
    priceTZS: 7500, // unit equivalent or bulk cost factor
    category: "Kids",
    baleSize: "25kg Pack",
    description: "Extremely high-grade, pre-washed infant romper and dress assortment.",
    expectedProfitMargin: 0.90,
    resalePotential: "Sell pack items at 2,000 TZS - 4,000 TZS each",
    targetCustomer: "Young moms, specialized baby stores",
  },
  {
    id: 12,
    name: "Children Medium Rummage 30KG",
    priceTZS: 10000,
    category: "Kids",
    baleSize: "30kg Pack",
    description: "Durable cotton clothing, T-shirts, trousers, and skirts for kids.",
    expectedProfitMargin: 0.85,
    resalePotential: "Sell pack items at 2,500 TZS - 5,000 TZS each",
    targetCustomer: "Primary schools area, local markets",
  },
  {
    id: 13,
    name: "Jogging Pants 25KG",
    priceTZS: 7500,
    category: "Sportswear",
    baleSize: "25kg Pack",
    description: "Comfortable fleece sweatpants and jogger pants.",
    expectedProfitMargin: 0.80,
    resalePotential: "Sell pack items at 15,000 TZS - 18,000 TZS each",
    targetCustomer: "Gyms, athletic youth",
  },
  {
    id: 14,
    name: "Leggings",
    priceTZS: 10000,
    category: "Sportswear",
    baleSize: "25kg",
    description: "High elastic sport and leisure leggings in pristine condition.",
    expectedProfitMargin: 0.70,
    resalePotential: "Sell individually at 18,000 TZS - 20,000 TZS",
    targetCustomer: "Fitness boutiques, daily wear",
  },
  {
    id: 15,
    name: "Mix T-Shirts",
    priceTZS: 13000,
    category: "T-Shirts",
    baleSize: "45kg / 55kg",
    description: "Branded and premium cotton crewneck and v-neck t-shirts.",
    expectedProfitMargin: 0.60,
    resalePotential: "Sell individually at 20,000 TZS - 25,000 TZS",
    targetCustomer: "Youth clothing kiosks, weekend pop-ups",
  },
  {
    id: 16,
    name: "Sportwear",
    priceTZS: 15000,
    category: "Sportswear",
    baleSize: "45kg",
    description: "Assorted track jackets, football jerseys, and workout tees.",
    expectedProfitMargin: 0.65,
    resalePotential: "Sell individually at 24,000 TZS - 28,000 TZS",
    targetCustomer: "Sports clubs, active wear stores",
  },
  {
    id: 17,
    name: "Ladies Handbags",
    priceTZS: 22000,
    category: "Handbags",
    baleSize: "30kg / 45kg",
    description: "Excellent designer, casual, and formal leather and fabric handbags.",
    expectedProfitMargin: 0.85,
    resalePotential: "Sell individually at 45,000 TZS - 60,000 TZS",
    targetCustomer: "Niche boutique stores, Instagram sellers",
  },
  {
    id: 18,
    name: "Sweatshirt Light",
    priceTZS: 11000,
    category: "T-Shirts",
    baleSize: "45kg",
    description: "Breathable cotton light sweatshirts and layering sweaters.",
    expectedProfitMargin: 0.70,
    resalePotential: "Sell individually at 20,000 TZS - 22,000 TZS",
    targetCustomer: "Daily retail shops",
  },
  {
    id: 19,
    name: "Leather Pants / Skirts [U]",
    priceTZS: 25000,
    category: "Leather",
    baleSize: "25kg",
    description: "Heavy premium sorted leather trousers and skirts with no tearing.",
    expectedProfitMargin: 0.90,
    resalePotential: "Sell individually at 50,000 TZS - 70,000 TZS",
    targetCustomer: "High-end alternative fashion, club wear boutique",
  },
  {
    id: 20,
    name: "Ladies Fashion Jackets [Leather]",
    priceTZS: 30000,
    category: "Leather",
    baleSize: "30kg / 45kg",
    description: "Tailored fit, real sorted leather jackets in premium dark shades.",
    expectedProfitMargin: 1.00,
    resalePotential: "Sell individually at 65,000 TZS - 90,000 TZS",
    targetCustomer: "Fashion boutiques, motor riders",
  },
  {
    id: 21,
    name: "Men Leather Jackets",
    priceTZS: 35000,
    category: "Leather",
    baleSize: "45kg",
    description: "Heavy authentic motorcycle and flight jackets in outstanding shape.",
    expectedProfitMargin: 0.95,
    resalePotential: "Sell individually at 75,000 TZS - 110,000 TZS",
    targetCustomer: "Distributors, bike clubs",
  },
  {
    id: 22,
    name: "Light Zipper Jackets",
    priceTZS: 16000,
    category: "Jackets",
    baleSize: "45kg",
    description: "Lightweight summer jackets, bomber jackets with full zippers.",
    expectedProfitMargin: 0.60,
    resalePotential: "Sell individually at 25,000 TZS - 30,000 TZS",
    targetCustomer: "High school youth, local daily workers",
  },
];

export const INITIAL_BALES: BaleOption[] = [
  {
    id: "bale-starter-25",
    name: "25kg Starter Bale",
    weight: "25kg",
    priceUSD: 130,
    priceTZS: 350000,
    idealCustomer: "New Entrepreneurs",
    estimatedPieces: 85,
    expectedResalePotential: "Earn up to 750,000 TZS total retail",
    storageRecommendation: "Compact, easily fits in standard home cabinets",
    profitOpportunity: "High turnover, low financial entry risk",
    badge: "Most Popular",
  },
  {
    id: "bale-business-30",
    name: "30kg Business Starter",
    weight: "30kg",
    priceUSD: 185,
    priceTZS: 500000,
    idealCustomer: "Instagram & TikTok Sellers",
    estimatedPieces: 110,
    expectedResalePotential: "Earn up to 1,200,000 TZS total retail",
    storageRecommendation: "Requires 1 standard warehouse shelf",
    profitOpportunity: "A+ Premium sorted, highly visual layouts",
  },
  {
    id: "bale-wholesale-45",
    name: "45kg Wholesale Bale",
    weight: "45kg",
    priceUSD: 260,
    priceTZS: 700000,
    idealCustomer: "Market Traders & Boutique Owners",
    estimatedPieces: 160,
    expectedResalePotential: "Earn up to 1,800,000 TZS total retail",
    storageRecommendation: "Standard storage room",
    profitOpportunity: "Best value, ideal mix of high volume & premium margin",
    badge: "Best Value",
  },
  {
    id: "bale-premium-55",
    name: "55kg Premium Business Bale",
    weight: "55kg",
    priceUSD: 335,
    priceTZS: 900000,
    idealCustomer: "Established Fashion Retailers",
    estimatedPieces: 210,
    expectedResalePotential: "Earn up to 2,500,000 TZS total retail",
    storageRecommendation: "Professional stock rails advised",
    profitOpportunity: "Loaded with High-Grade European 'Cream' stock",
  },
  {
    id: "bale-commercial-70",
    name: "70kg Commercial Bale",
    weight: "70kg",
    priceUSD: 445,
    priceTZS: 1200000,
    idealCustomer: "County Distributors & Wholesalers",
    estimatedPieces: 280,
    expectedResalePotential: "Earn up to 3,500,000 TZS total retail",
    storageRecommendation: "Warehouse space or heavy garage racks",
    profitOpportunity: "Maximum profitability per kilogram imported",
  },
];
